#!/bin/bash

###################################################################################################################################
# Date: 2021/01
# Author: Fabrice MOYEN
# Objective: Apply Security Rules


###################################################################################################################################
# Parameters
#

WhoAmI=`who am i| awk '{print $1}'` # "whoami" not working because of sudo


###################################################################################################################################
# Functions
#

function usage
{
  echo
  echo "`basename $0` Usage:"
  echo "-------------------------"
  echo
  echo "  + script to be run on the system you want to tune"
  echo
  echo "  + You need to be root to use the script (sudo)"
  echo
  echo "  + Objective: Apply all Security Rules"
  echo "  + -h / -? / --help: shows this usage info"
  echo
  exit 0
}


###################################################################################################################################
# When parameters are given when launching the script
#

if [ $# -gt 0 ]
then
  WhatToDo=$1
  if [ "$WhatToDo" == "-h" ] || [ "$WhatToDo" == "-?" ] || [ "$WhatToDo" == "--help" ]; then
    usage
  fi
fi


###################################################################################################################################
# Check if root
#

if [ `whoami` != "root" ]
then
  echo
  echo "You're not root. You need to execute this script with root privileges"
  echo "Think of sudo command..."
  echo "Exiting"
  exit 0
fi


###################################################################################################################################
# MAIN
#
echo; echo "###################################################################################################################################"
hostname | tr '[:lower:]' '[:upper:]'
echo "-----------------------------------------------------------------------------------------------------------------------------------"
echo "$WhoAmI --> `basename $0` "
date
echo "###################################################################################################################################"; echo

ScriptDir=$(dirname $0)

echo; echo "###################################################################################################################################"
echo $ScriptDir/Apply90DaysLog; echo
$ScriptDir/Apply90DaysLog

echo; echo "###################################################################################################################################"
echo $ScriptDir/ApplyPasswordRules; echo
$ScriptDir/ApplyPasswordRules

echo; echo "###################################################################################################################################"
echo $ScriptDir/ApplySSHRootLogin; echo
$ScriptDir/ApplySSHRootLogin; echo
