#!/bin/bash

##############################################################################################
# Get all existing users (who can login) per system
# One file per system

Hosts=`cat ../../ipmi/PasswordFile | awk '{print $1}'`
ListDir=/home/fabrice/capi/ARCHITECTURE/SECURITY/ExistingUsersList/LISTS
echo; echo "--------------------"
echo "List of systems:"
echo $Hosts
echo; echo "--------------------"
echo "Output directory:"
echo $ListDir

for i in $Hosts; do
   echo; echo "--------------------"
   echo $i
   Hostname=$i
   ssh fmoyen@$i "grep \"sh$\" /etc/passwd" | awk -F: '{print $1}' | grep -v root > $ListDir/ExistingUsersList_$Hostname.txt
   echo "  --> $ListDir/ExistingUsersList_$Hostname.txt"
done
echo "--------------------"; echo
