#!/bin/bash

##############################################################################################
# Get all existing users (who can login) per system
# One file per system

Hosts=`cat ../../ipmi/PasswordFile | awk '{print $1}'`
ListDir=/home/fabrice/capi/ARCHITECTURE/SECURITY/ExistingUsersList/LISTS
echo $Hosts

for i in $Hosts; do
   echo $i
   echo "--------------------"
   Hostname=$i
   ssh fmoyen@$i "grep \"sh$\" /etc/passwd" | awk -F: '{print $1}' | grep -v root > $ListDir/ExistingUsersList_$Hostname.txt
done
