#!/bin/bash


# Objective is to delete 
#   - too old FPGA images
# Author: Fabrice MOYEN
# Date: 2019/12/05
# Updates: 2020/06/30 (now taking into account links)
# Updates: 2022/01/11 Several types given to find command at the same time like in "-type f,l" is not always supported (mopjenkins OK, not jtagx86)

#---------------------------------------------------------------

ImagesDir=/data/Images
OlderThanXDays=30

if [ $# -ne 0 ]; then
	Delete=0
else
	Delete=1
fi


#---------------------------------------------------------------
echo;echo "***************************************************************************************************"
echo "Images Directory: $ImagesDir"
echo;echo "***************************************************************************************************"

if [ $Delete -eq 1 ]; then
	echo "  -> Deleting FPGA binary images which modifications are older than $OlderThanXDays days..."
	echo
	#find $ImagesDir -type f,l -mtime +$OlderThanXDays -exec rm {} \; -print
	find $ImagesDir -type f -mtime +$OlderThanXDays -exec rm {} \; -print
	find $ImagesDir -type l -mtime +$OlderThanXDays -exec rm {} \; -print

	echo;echo "***************************************************************************************************"
	echo "  -> Deleting empty directories..."
	echo
	for i in `ls -d $ImagesDir/*/*/`; do
		if [ -z "$(ls -A $i)" ]; then
			echo $i
			rmdir $i
	  	fi
	done
	for i in `ls -d $ImagesDir/*/`; do
		if [ -z "$(ls -A $i)" ]; then
			echo $i
			rmdir $i
	  	fi
	done
else
	echo "  -> Showing (but not deleting) FPGA binary images which modifications are older than $OlderThanXDays days..."
	echo
	#find $ImagesDir -type f,l -mtime +$OlderThanXDays -exec ls -la {} \; -print
	find $ImagesDir -type f -mtime +$OlderThanXDays -exec ls -la {} \; -print
	find $ImagesDir -type l -mtime +$OlderThanXDays -exec ls -la {} \; -print
fi

echo;echo "***************************************************************************************************"

